const constants = {
	ADD_DIDYOUMEAN: "ADD_DIDYOUMEAN",
	CLEAR_DIDYOUMEAN: "CLEAR_DIDYOUMEAN",
	CHANGE_SEARCH:"CHANGE_SEARCH",
	CLEAR_SEARCH: "CLEAR_SEARCH",
	ADD_SUGGESTIONS: "ADD_SUGGESTIONS",
	CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS",
	ADD_NEWS: "ADD_NEWS",
	CLEAR_NEWS:"CLEAR_NEWS",
	EDIT_NEWS: "EDIT_NEWS",
	SET_PAGESIZE: "SET_PAGESIZE",
	CLEAR_PAGESIZE:"CLEAR_PAGESIZE",
	SET_NEXTTOKEN:"SET_NEXTTOKEN",
	CLEAR_NEXTTOKEN:"CLEAR_NEXTTOKEN",
	SET_PREVIUSTOKEN:"SET_PREVIUSTOKEN",
	CLEAR_PREVIUSTOKEN:"CLEAR_PREVIUSTOKEN",
	SET_ACTUALPAGE:"SET_ACTUALPAGE",
	CHANGE_ACTUALPAGE: "CHANGE_ACTUALPAGE"
}

export default constants