const constants = {
	ADD_DIDYOUMEAN: "ADD_DIDYOUMEAN",
	CLEAR_DIDYOUMEAN: "CLEAR_DIDYOUMEAN",
	CHANGE_SEARCH:"CHANGE_SEARCH",
	CLEAR_SEARCH: "CLEAR_SEARCH",
	ADD_SUGGESTIONS: "ADD_SUGGESTIONS",
	CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS",
	ADD_NEWS: "ADD_NEWS",
	ADD_NEWS_BULK: "ADD_NEWS_BULK",
	REMOVE_NEWS:"REMOVE_NEWS",
	EDIT_NEWS: "EDIT_NEWS",
	CANCEL_EDIT : "CANCEL_EDIT",
	SET_PAGESIZE: "SET_PAGESIZE",
	SET_NEXTTOKEN:"SET_NEXTTOKEN",
	SET_PREVIUSTOKEN:"SET_PREVIUSTOKEN",
	SET_ACTUALPAGE:"SET_ACTUALPAGE",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR"
}

export default constants